#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# License: GNU General Public License v2

import sys

from cmk_addons.plugins.netapp_eseries.special_agents.agent_netappeseries import main

if __name__ == "__main__":
    sys.exit(main())
