#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

from typing import Any, Mapping, Optional, Sequence

from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info


def agent_netappeseries_arguments(
    params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[str]:
    '''build command line arguments'''
    return [
        "-u",
        f"{params['user']}",
        "-s",
        passwordstore_get_cmdline("%s", params["password"]),
        *(["--port", f"{params['port']}"] if "port" in params else []),
        *(["--proto", f"{params['proto']}"] if "proto" in params else []),
        *(["--system-id", f"{params['system-id']}"] if "system-id" in params else []),
        *(["--sections", f",".join(params["sections"])] if "sections" in params else []),
        ipaddress or hostname,
    ]


special_agent_info['netappeseries'] = agent_netappeseries_arguments
