#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def agent_netappeseries_arguments(params, hostname, ipaddress):
    args = ''
    if params["user"] != "":
        args += "-u " + quote_shell_string(params["user"])
    if params["password"] != "":
        args += " -s " + quote_shell_string(params["password"])
    if 'proto' in params and params["proto"] != "":
        args += " --proto " + params["proto"]
    if 'port' in params and params["port"] != "":
        args += " --port " + str(params["port"])
    if 'system-id' in params and params["system-id"] != "":
        args += " --system-id " + str(params["system-id"])
    if 'sections' in params and params["sections"] != "":
        args += " --sections " + ",".join(params["sections"])

    args += " " + quote_shell_string(ipaddress)
    return args


special_agent_info['netappeseries'] = agent_netappeseries_arguments
