#!/usr/bin/env python2
# -*- encoding: utf-8; py-indent-offset: 4 -*-

from typing import Any, Mapping, Optional, Sequence

from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info

def agent_emcunity_arguments( params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]) -> Sequence[str]:
    '''build command line arguments'''

    return [

        *(["-u", f"{params['username']}"] if "username" in params else []),
        *(["-p", passwordstore_get_cmdline("%s", params["password"])] if "password" in params else []),
        ipaddress or hostname
        ]

special_agent_info['emcunity'] = agent_emcunity_arguments
